//
// Generated file, do not edit! Created by opp_msgc 4.4 from Message.msg.
//

#ifndef _MESSAGE_M_H_
#define _MESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Message.msg</tt> by opp_msgc.
 * <pre>
 * message Message {
 *        int dst;
 *        int src;
 *        int sessionId;
 *        int packetId;
 *        int priority;
 *        int payload;
 * }
 * </pre>
 */
class Message : public ::cMessage
{
  protected:
    int dst_var;
    int src_var;
    int sessionId_var;
    int packetId_var;
    int priority_var;
    int payload_var;

  private:
    void copy(const Message& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Message&);

  public:
    Message(const char *name=NULL, int kind=0);
    Message(const Message& other);
    virtual ~Message();
    Message& operator=(const Message& other);
    virtual Message *dup() const {return new Message(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getDst() const;
    virtual void setDst(int dst);
    virtual int getSrc() const;
    virtual void setSrc(int src);
    virtual int getSessionId() const;
    virtual void setSessionId(int sessionId);
    virtual int getPacketId() const;
    virtual void setPacketId(int packetId);
    virtual int getPriority() const;
    virtual void setPriority(int priority);
    virtual int getPayload() const;
    virtual void setPayload(int payload);
};

inline void doPacking(cCommBuffer *b, Message& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Message& obj) {obj.parsimUnpack(b);}


#endif // _MESSAGE_M_H_
